import type { TeamMember } from "./types";

export const PERSONAS = [
  { id: "maya-chen", displayName: "Maya Chen", role: "CEO", traits: { dominance: 88, risk_appetite: 78, decisiveness: 84, ambition: 55, analytical_depth: 58, ambiguity_tolerance: 82, innovation: 76, strategic_horizon: 86, interpersonal_sensitivity: 48, influence_style: 74, conflict_approach: 82, trust_disposition: 61, composure: 73, control_retention: 81, optimism_bias: 78, accountability: 85 } },
  { id: "elena-rossi", displayName: "Elena Rossi", role: "COO", traits: { dominance: 80, risk_appetite: 42, decisiveness: 79, ambition: 48, analytical_depth: 74, ambiguity_tolerance: 57, innovation: 38, strategic_horizon: 52, interpersonal_sensitivity: 63, influence_style: 46, conflict_approach: 67, trust_disposition: 44, composure: 84, control_retention: 72, optimism_bias: 46, accountability: 88 } },
  { id: "priya-nair", displayName: "Priya Nair", role: "CFO", traits: { dominance: 46, risk_appetite: 24, decisiveness: 57, ambition: 42, analytical_depth: 92, ambiguity_tolerance: 34, innovation: 29, strategic_horizon: 68, interpersonal_sensitivity: 71, influence_style: 32, conflict_approach: 30, trust_disposition: 26, composure: 76, control_retention: 67, optimism_bias: 28, accountability: 91 } },
  { id: "tom-bennett", displayName: "Tom Bennett", role: "CTO", traits: { dominance: 58, risk_appetite: 69, decisiveness: 54, ambition: 50, analytical_depth: 88, ambiguity_tolerance: 79, innovation: 91, strategic_horizon: 74, interpersonal_sensitivity: 35, influence_style: 39, conflict_approach: 74, trust_disposition: 57, composure: 51, control_retention: 43, optimism_bias: 66, accountability: 72 } },
  { id: "amina-yusuf", displayName: "Amina Yusuf", role: "General Counsel", traits: { dominance: 52, risk_appetite: 27, decisiveness: 59, ambition: 35, analytical_depth: 86, ambiguity_tolerance: 45, innovation: 31, strategic_horizon: 71, interpersonal_sensitivity: 78, influence_style: 58, conflict_approach: 41, trust_disposition: 30, composure: 87, control_retention: 64, optimism_bias: 33, accountability: 89 } },
  { id: "lucas-silva", displayName: "Lucas Silva", role: "CRO", traits: { dominance: 76, risk_appetite: 83, decisiveness: 81, ambition: 90, analytical_depth: 43, ambiguity_tolerance: 77, innovation: 68, strategic_horizon: 62, interpersonal_sensitivity: 67, influence_style: 91, conflict_approach: 69, trust_disposition: 73, composure: 61, control_retention: 74, optimism_bias: 84, accountability: 64 } },
  { id: "noor-haddad", displayName: "Noor Haddad", role: "CPO", traits: { dominance: 61, risk_appetite: 63, decisiveness: 52, ambition: 76, analytical_depth: 69, ambiguity_tolerance: 74, innovation: 89, strategic_horizon: 81, interpersonal_sensitivity: 86, influence_style: 82, conflict_approach: 48, trust_disposition: 68, composure: 67, control_retention: 38, optimism_bias: 71, accountability: 78 } },
  { id: "daniel-okafor", displayName: "Daniel Okafor", role: "VP Engineering", traits: { dominance: 37, risk_appetite: 33, decisiveness: 41, ambition: 38, analytical_depth: 84, ambiguity_tolerance: 49, innovation: 62, strategic_horizon: 40, interpersonal_sensitivity: 73, influence_style: 36, conflict_approach: 25, trust_disposition: 64, composure: 42, control_retention: 29, optimism_bias: 39, accountability: 82 } },
  { id: "sofia-petrov", displayName: "Sofia Petrov", role: "Chief People Officer", traits: { dominance: 44, risk_appetite: 38, decisiveness: 47, ambition: 64, analytical_depth: 61, ambiguity_tolerance: 58, innovation: 55, strategic_horizon: 65, interpersonal_sensitivity: 93, influence_style: 87, conflict_approach: 36, trust_disposition: 79, composure: 71, control_retention: 24, optimism_bias: 62, accountability: 75 } },
  { id: "james-whitfield", displayName: "James Whitfield", role: "Chair", traits: { dominance: 84, risk_appetite: 48, decisiveness: 73, ambition: 71, analytical_depth: 72, ambiguity_tolerance: 66, innovation: 40, strategic_horizon: 91, interpersonal_sensitivity: 54, influence_style: 70, conflict_approach: 77, trust_disposition: 35, composure: 89, control_retention: 86, optimism_bias: 44, accountability: 68 } },
] satisfies readonly TeamMember[];

export const DEMO_TEAM = ["maya-chen", "elena-rossi", "priya-nair", "tom-bennett", "amina-yusuf"] as const;
